from pydantic import BaseModel, Field
from typing import List

class ChatRequest(BaseModel):
    query: str = Field(..., description="The user question or request text")
    document_id: str = Field(..., description="The unique ID of the document to restrict retrieval to")

class ChatSource(BaseModel):
    filename: str = Field(..., description="The source PDF filename")
    page_number: int = Field(..., description="The page number where the chunk resides")
    chunk_index: int = Field(..., description="The index position of the chunk in the document")

class ChatResponse(BaseModel):
    answer: str = Field(..., description="The grounded RAG answer generated by the model")
    sources: List[ChatSource] = Field(..., description="List of unique source chunks used for context")
